name: CSU Library CheckIn

on:
  workflow_dispatch:

  schedule:
    - cron: '30 23 * * *' #北京时间7:30
    
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: CheckIn
      run: |
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        python3 helper.py --action 'checkIn' --userid $user --password $pwd
    - name: Commit
      run: |
        git config --global user.email ntlxz1001@163.com
        git config --global user.name LXZrivendell
        git add .
        git commit -m "Update library.log" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
